[server]
port = 8000
address = "127.0.0.1"
enableCORS = true
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#c60dff"
backgroundColor = "#171d30"
secondaryBackgroundColor = "#5900f2"
textColor = "#ffffff"
font = "sans serif"

[client]
caching = true
showErrorDetails = false

[browser]
serverAddress = "127.0.0.1"
serverPort = 8000

[runner]
fastReruns = true
